### ISSUE TITLE
Incorrect params parsing of basic API.

### ISSUE THREAD

**Issue by information-security** [binary-com/deriv-api#105]
This line causes problems with the methods that accept decimal numbers such as `proposal`. For instance, if you set the `amount` value of the `proposal` function to `0.35`, it will be parsed to `0` which will result in an error (_Please enter a stake amount that's at least 0.35_) while it is totally a valid API call.

https://github.com/binary-com/deriv-api/blob/b4d2899ef6afe022860ff2cbbd08bc37a8574889/src/deriv_api/DerivAPICalls.js#L5886

**Comment by chylli-binary** [comment]
This problem is fixed [here](https://github.com/binary-com/deriv-api/pull/117) and can be closed.
Thanks for your report @information-security
