### ISSUE TITLE
api.contract blocks after requests of the same contract type

### ISSUE THREAD

**Issue by lordzouga** [binary-com/deriv-api#133]
hello, if I make 2 requests in a row on the same connection with the same contract_type, the second call blocks
`await api.contract({
                contract_type: curTradeType,
                symbol: 'R_10',
                duration: 5,
                duration_unit: 't',
                barrier: barrierOffset,
                basis: 'stake',
                currency: 'USD',
                amount: 50
            });`

If I make two 'CALL' requests, the first on is successful but the second one blocks with no response at all, not even an error message.

**Comment by QuisEgoSum** [comment]
Have you managed to solve this problem?

**Comment by lordzouga** [comment]
yeah, you have to call `api.basic.forget(proposal_id)` after each contract is sold. `proposal_id` is the proposal id of the sold contract.

**Comment by QuisEgoSum** [comment]
Thanks!
