### ISSUE TITLE
Question about js-interpreter in npm -- from the js-interpreter team

### ISSUE THREAD

**Issue by mercmobily** [binary-com/deriv-api#15]
Hi Amin,

I apologise for contacting you here, but I just couldn't find your email address anywhere.

We would like to manage our own NPM packge releases for [JS-Interpreter](https://github.com/NeilFraser/JS-Interpreter). At the moment, anybody using NPM would assume your package is the official one -- although it's a fork, and it hasn't been updated for about 3 years.

Would it be OK for you to hand over the js-interpreter NPM domain so that we can start using it?

Sorry to pollute this unrelated issue list again.

We haven't updated our homepage yet, but will do that once we get an answer from you.

Thank you!

Merc.

**Comment by aminmarashi-binary** [comment]
Hi, I replied to the issue on the original `js-interpreter` repo, I'm closing this issue.
