### ISSUE TITLE
TypeError: account.contract is not a function

### ISSUE THREAD

**Issue by victorfds** [binary-com/deriv-api#18]
```javascript
const account = await api.account(token);
const contract = account.contract({ 
    contract_type: 'CALL',
    amount: 10,
    duration: 5,
    duration_unit: 't',
    symbol: 'frxUSDJPY',
    basis: 'stake'
 });
```

Error when trying to access contract from account

**Comment by lechim** [comment]
Hi @victorfds, by the looks of it in the api docs it must be account.contract

**Comment by victorfds** [comment]
> Hi @victorfds, by the looks of it in the api docs it must be api.contract not account.contact.

Hi, @lechim , Thank you for the help. 
I'll try it.
