### ISSUE TITLE
Binary-live-api vs Deriv

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/deriv-api#38]
Hi Guys, 

I'm an app developer using the binary-live-api. I would like to update the application to support the new margin trading method, is this supported in binary-live-api? Also will the old api end up being depricated in favour of this one?

Basically, should I be refactoring and migrating my applications over to Deriv-api?

Many thanks in advance!

Will

**Comment by salar-fs** [comment]
Hey!
Yep better to upgrade soon. The reason for this is one of the dependencies of `binary-live-api` task runner (gulp) is deprecated and we can do nothing regarding this.
