### ISSUE TITLE
Cancel a contract through the API

### ISSUE THREAD

**Issue by victorfds** [binary-com/deriv-api#42]
How to **[cancel](https://developers.binary.com/api/#cancel)** a contract through the API?
I realized that neither **[Deriv API](https://github.com/binary-com/deriv-api/)** nor **[Binary API](https://github.com/binary-com/binary-live-api)** has access to this mechanism.

**Comment by salar-fs** [comment]
For [Deriv API](https://github.com/binary-com/deriv-api/) you can use:
`api.basic.send({ cancel: contract_id })`

**Comment by victorfds** [comment]
Thank you, @salar-fs .
